//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Cust_id { get; set; }
        public string Cust_Name { get; set; }
        public string Address { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
        public System.DateTime Creation_date { get; set; }
    }
}
